### ISSUE TITLE
Add component of moha_ui_rating error

### ISSUE THREAD

**Issue by moha-art-dev** [MohaOnline/moha#7]
TypeError: Argument 2 passed to _webform_edit_moha_ui_rating() must be of the type array, none given, called in .../sites/all/modules/contrib/webform/webform.module on line 4727 in _webform_edit_moha_ui_rating() (line 38 of .../sites/all/modules/custom/moha/modules/moha_ui/webform/components/moha_ui_rating.inc).

**Comment by moha-art-dev** [comment]
Tried fix the error in
https://github.com/MohaOnline/moha/pull/8

**Comment by ma3310** [comment]
How to reappear this issue?

**Comment by ma3310** [comment]
How to reappear this issue? If it's caused by creating moha_ui_rating programmatically, maybe it's because mandatory extra parameters are missing. let's track progress in #4
